### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hounsellal** [lgromanowski/letsencrypt-plugin#19]
I've created the YML file in config and created the keyfile.pem and certificates folders. 

When I run rake letsencrypt_plugin:install:migrations, this is the output:

rake aborted!
SyntaxError: /Library/Ruby/Gems/2.0.0/gems/acme-client-0.2.4/lib/acme/client.rb:12: syntax error, unexpected ','
  def initialize(private_key:, endpoint: DEFAULT_ENDPOINT, ...

**Comment by lgromanowski** [comment]
Hi,
please update your ruby version in Gemfile acme-client requires ruby >= 2.1
