### ISSUE TITLE
letsencrypt_plugin.yml should be added before running the migrations.

### ISSUE THREAD

**Issue by keating** [lgromanowski/letsencrypt-plugin#20]
Otherwise I get the error
`No such file or directory @ rb_sysopen - /Users/.../invest/config/letsencrypt_plugin.yml`

I just think `README.md` should be updated.

**Comment by dwcaraway** [comment]
I think this has been addressed by installation guide which is now referenced by the `README.md`: https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide/2474c318a38b66b4c26dcb4b3f69ae28375b4954
