### ISSUE TITLE
how to encrypt two domains at the same time?

### ISSUE THREAD

**Issue by keating** [lgromanowski/letsencrypt-plugin#21]
For example, `mydomain.com` and `www.mydomain.com`

When using the letsencrypt command, `-d` should be used twice.

`./letsencrypt-auto certonly --webroot -w /var/www/default -d mydomain.net -d www.mydomain.net`

**Comment by lgromanowski** [comment]
Hi,
at this moment it's not possible - I'm going to add this in next version which should be released tomorrow.

**Comment by acorncom** [comment]
Is this something you still want to do?  If you have time to write up some guidance on how you'd like to see it done, I may be able to handle this as part of work for a client ...

**Comment by lgromanowski** [comment]
Hi,
I think it's already handled - https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide#2a-multiple-domains 

I'll close this issue (please re-open if needed)
