### ISSUE TITLE
letsencrypt routes doesn't seem to be working

### ISSUE THREAD

**Issue by jack-mcgrath** [lgromanowski/letsencrypt-plugin#22]
First of all, I love this project!
The issue that I'm having is that  the /.well-known/acme-challenge/:challenge route is 404'ing. 
When I run rake routes, the letsencrypt plugin engine route doesn't show up, could that mean anything?
My rake routes is exactly as specified:
```
Rails.application.routes.draw do
  mount LetsencryptPlugin::Engine, at: '/'
...
end
```
Here's the error from running the plugin.
`E, [2016-01-28T01:57:04.004555 #49047] ERROR -- : Challenge verification failed! Error: urn:acme:error:unauthorized: Invalid response from http://[domainname.com]/.well-known/acme-challenge/WKLyr2JbtUaWBTrQ2Gsk97467rhwAoJEkY98YexNwGc [54.83.9.155]: 404`

Any ideas would be appreciated!

**Comment by lgromanowski** [comment]
Hi,
please check if you restarted rails application after adding new route: ```touch tmp/restart.txt```

**Comment by jack-mcgrath** [comment]
Resolved. Thank you!
