### ISSUE TITLE
Does the private key have to be versioned and pushed to Heroku?

### ISSUE THREAD

**Issue by olivierlacan** [lgromanowski/letsencrypt-plugin#31]
If someone breaches the source code, they will be able to generate a new SSL certificate. That seems like an issue.

Is there a way to avoid doing that with this plugin?

Thank you :-)

**Comment by lgromanowski** [comment]
Hi,
I know that current solution could be a risk, at this moment there is no other way, but I'm going to add possibility to retrieve a private key from DB, so it should be a little bit safer on Heroku-like environment.

**Comment by olivierlacan** [comment]
Ok, thanks. I'll close this for now. :-)

**Comment by simonv3** [comment]
I'm guessing this means that to use this the private key needs to be part of the repository? (bit of a crypto noob)

**Comment by lgromanowski** [comment]
You can store private key in DB ("private_key_in_db: true" in config file and "private_key" field in DB) if you don't want to store it in repository

**Comment by simonv3** [comment]
:thumbsup: That's related to my MongoDB question, so I'll see if I can write a PR for that. Thanks for the quick feedback and responses @lgromanowski!
