### ISSUE TITLE
How to renew a cert ?

### ISSUE THREAD

**Issue by keating** [lgromanowski/letsencrypt-plugin#32]
How to renew a cert, is there instruction ? Or do it again as the `Usage` instruction ?

**Comment by lgromanowski** [comment]
Please do it as in usage instruction - it will generate new certificate

**Comment by MincePie** [comment]
Did you figure out how to renew the SSL? Which steps specifically need to be repeated? New migrations? new file directories? Thank you

**Comment by lgromanowski** [comment]
You just have to run letsencrypt_plugin task again - it should generate new certificate

**Comment by niiicolai** [comment]
I did it the following way.
https://gist.github.com/niiicolai/267d0b74e5c1b0718895ba42b57c448b

**Comment by MincePie** [comment]
I have 2 certificates under the heading INFO -- : ====== www..com-fullchain.pem ======

If I try to use both, I get an error that says line break. If I just use one (I've tried using each), but then I get an error that says: 

 ENOENT: ENOENT: no such file or directory, open
 ▸    'PATH/www..com-fullchain.pem'

Are there step by step instructions to update a certificate?

**Comment by lgromanowski** [comment]
Hi,
you should use ```domainname-fullchain.pem``` certificate generated in the same way like for the first time. There are no special instructions for the renewing certificate.

**Comment by MincePie** [comment]
I wasn't able to make sense of the instructions - but it doesn't matter anymore - Im now using heroku AMS. Thanks anyway. if others struggle with similar issues, perhaps you might clarify which of the 2 certs described above should be used.
