### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by halo** [lgromanowski/letsencrypt-plugin#35]
Several people are forking this gem to [do just one thing](https://github.com/dudo/letsencrypt-plugin/commit/823977ed428e7ad93b1e5a80cfe26b36f177f9dc): Change the rails dependency from `~> 4` to `>= 4` so as to allow for Rails 5.

I see that there is an (outdated) `rails5` branch. Is there any reason for not changing at least the Rails version dependency in master?

**Comment by mathieujobin** [comment]
PR #37

**Comment by Spone** [comment]
@lgromanowski hi, the PR has been merge, so I think you can close this issue.

**Comment by mathieujobin** [comment]
@halo can also close it 

thanks for the merge @lgromanowski

**Comment by lgromanowski** [comment]
Closing, thanks!

**Comment by halo** [comment]
By the way, it would be nice to see this published on rubygems.org as well. The latest version there (0.0.8 from March 2016) doesn't have this fix.

Thank you!

**Comment by lgromanowski** [comment]
Hi,
I'm going to spend some time on letsencrypt_plugin next week, so I think I'll do a 0.0.9 release then.
