### ISSUE TITLE
Allow editing the Wiki

### ISSUE THREAD

**Issue by e2** [lgromanowski/letsencrypt-plugin#38]
#### 1. Expected behavior
If I encounter undocumented problems and solutions, I want to be able to add them to the Wiki.

#### 2. Actual behavior 
Wiki pages cannot be edited.

#### 3. Steps to reproduce issue
Go to Wiki and look for edit button. None ;(

#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

Doesn't matter, lol... Except that I use Rails 4.x maybe.

#### Issues

There's little risk in letting people edit the Wiki:

1. Removed content can be restored (by cloning the wiki branch and reverting).
2. Anyone making changes is in the commit history - if someone tries something nasty, you can report them to GitHub staff anyway.
3. Most people using this project are mostly experts with very useful tips - so any mistakes will be spotted quickly and fixed.
4. It doesn't make sense to have issues opened for Wiki entries
5. You can always add disclaimers about the Wiki, etc.
6. People have different setups - and they can add special pages for them anyway.

**Comment by lgromanowski** [comment]
Hi,
thanks for pointing this out - wiki editing is now enabled.
