### ISSUE TITLE
File storage fails on Heroku: Errno::ENOENT (No such file or directory @ rb_sysopen - /app/challenge/challenge)

### ISSUE THREAD

**Issue by e2** [lgromanowski/letsencrypt-plugin#39]
#### 1. Expected behavior

It just works.

#### 2. Actual behavior 

Does not store challenge.

Heroku error:

```
app[web.1]: Errno::ENOENT (No such file or directory @ rb_sysopen - /app/challenge/challenge):
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/letsencrypt_plugin-0.0.8/app/models/letsencrypt_plugin/challenge.rb:13:in `read'
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/letsencrypt_plugin-0.0.8/app/models/letsencrypt_plugin/challenge.rb:13:in `initialize'
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/letsencrypt_plugin-0.0.8/app/controllers/letsencrypt_plugin/application_controller.rb:20:in `new'
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/letsencrypt_plugin-0.0.8/app/controllers/letsencrypt_plugin/application_controller.rb:20:in `challenge_response'
```

No `challenge` file was created:

```
$ heroku run find /app/challenge/
Running find /app/challenge/ on foobar... up, run.1972
/app/challenge/
/app/challenge/.keep
```
(.keep was created by me)

#### 3. Steps to reproduce issue

1. Add empty challenge directory.
2. Run `heroku run rake letsencrypt_plugin`
3. Logs say that challenge is stored, but ...
4.  ... no challenge file on remote server

This is because creating files silently fails on heroku (it's a read-only filesystem). The workaround would be to e.g. set `challenge_dir_name` to something writable like `tmp/challenge' instead or fail with a better error (saying that the challenge should be generated locally and added to git). 

#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

Relevant part of config:
```
# (...)
challenge_dir_name: 'challenge'
# (...)
```

**Comment by lgromanowski** [comment]
Hi,
please use DB storage for Heroku: https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide#3-install-letsencrypt_plugin-migration

**Comment by simonv3** [comment]
So does this mean that an app that doesn't use ActiveRecord (ie it uses MongoID) won't work with this gem?

**Comment by lgromanowski** [comment]
At this moment it won't work (pull request with patches are welcome)
