### ISSUE TITLE
Dynamic Multiple domains: *.example.com

### ISSUE THREAD

**Issue by Roko131** [lgromanowski/letsencrypt-plugin#40]
My rails site creates a dynamic sub-domain for every new client-
Is it possible to also, dynamically add a sub-domain? or make it accept all (sub)domains without manually adding them to Rails.root/config/letsencrypt_plugin.yml file?

#### 1. Expected behavior
Enabling ALL sub-domains. something like *.example.com.

#### 2. Actual behavior 
As written in 2a:
For every new (sub)domain  add them separated by space to Rails.root/config/letsencrypt_plugin.yml
`domain: example.com www.example.com other.example.com`

Thank you

**Comment by lgromanowski** [comment]
Hi,
I'm sorry but I think it's not possible with letsencrypt-plugin to accept all sub-domains without manually adding them to the configuration file.

**Comment by sclarkin** [comment]
Just another vote for this. We too are in the same situation where a sub-domain is created for a new account in the system.

It would be handy to allow a list of domains to be passed to the `letsencrypt_plugin` task. One could then write a wrapper tasks that fetched the list dynamically and call the `letsencrypt_plugin` task with the list.

**Comment by jasper-lyons** [comment]
I've made a pull request that should allow this to work (though it requires updating the certificate after every additional subdomain is added), see [here](https://github.com/lgromanowski/letsencrypt-plugin/pull/45)

**Comment by Roko131** [comment]
Thank you,

Can you please show an example how to use it?
For example after a new subdomain requires certificate= which steps should be followed to dynamically add it to `lets encrypt` ?

**Comment by jasper-lyons** [comment]
The documentation should be updated [now](https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide#2a-multiple-domains)

That aside, could I have a little more context into your particular situation? e.g. where are you're dynamic subdomains stored?

I will provide an example for the db here:

```erb
default:
    domains: '<%= ModelWithSubdomains.pluck(:subdomain).map {|s| "#{s}.mydomain.com"}.join(' ') %>'
```

I about to implement this and so will update this once I've confirmed it works as expected.

**Comment by Roko131** [comment]
subdomains are stored in the DB, just as you showed-  this I understand.

What I don't understand is how to make that change take effect?
so after a new domain was added to the DB. How do I trigger the change?

**Comment by jasper-lyons** [comment]
I see. I suspect you would need to follow the instructions from [step 4](https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide#4-create-private-key)

I will be trying this out over the next hour or two so I will update you if it doesn't work :)

**Comment by jasper-lyons** [comment]
There is an issue when accessing a model during initialization before migration have occurred. This causes a `ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:` error.

I will submit another pull request with changes that fix this by lazy loading the config at run time instead of initialization.

**Comment by jasper-lyons** [comment]
That fix has been merged in now

**Comment by Roko131** [comment]
So if I understand correctly, after a new subdomain was added to database:
A server restart (step 7) will trigger the neccessary steps for the new sub to be fully working with SSL?

**Comment by jasper-lyons** [comment]
So far as I understand, yes.

After completing the steps you'll need to run:

`rake letsencrypt_plugin`

Task and use the certificates appropriately.

**Comment by Roko131** [comment]
That make sense.
Thank you very much.

**Comment by jasper-lyons** [comment]
No problem! Update here if anything doesn't work. :)

**Comment by jasper-lyons** [comment]
@lgromanowski this is probably closable?

**Comment by steveclarkin** [comment]
I just tested this, and it works a treat! Thanks!

**Comment by lgromanowski** [comment]
Great, thanks! :)
