### ISSUE TITLE
letsencrypt-plugin v0.0.8 doesn't work with Rails 5 :(

### ISSUE THREAD

**Issue by claudevandort** [lgromanowski/letsencrypt-plugin#41]
I'm using ruby 2.3.1 and Rails 5.0.0, but when I include the gem on my gemfile `gem 'letsencrypt_plugin', '~> 0.0.8'` I get to fetch the 0.0.8 version of the gem, but I'm getting an error saying that it depends on Rails 4.2.5 and even though the gem's gemspec file defines a dependency as Rails 5.1 max, in rubygems the dependency still seems to be 4.2.5

I hope you can check that.

Cheers!

**Comment by lgromanowski** [comment]
Hi,
strange, I'll check it. Thanks for reporting

**Comment by lgromanowski** [comment]
Hi,
changes related to Rails 5 are in a master branch and aren't released yet, so this is the reason why you see Rails 4.2.5 on rubygems. Please use:
```
gem 'letsencrypt-plugin', git: 'https://github.com/lgromanowski/letsencrypt-plugin.git', branch: 'master'
```
in your Gemfile if you want Rails 5 support enabled.
