### ISSUE TITLE
LetsencryptPlugin::ApplicationController#index renders an empty file

### ISSUE THREAD

**Issue by b264** [lgromanowski/letsencrypt-plugin#43]
#### 1. Expected behavior

Visiting `/.well-known/acme-challenge/y7HlW6w374Fom8VDkic8mk9LqWXKotNVjNo7Wc1Lo1E` renders a challenge token
#### 2. Actual behavior

Visiting `/.well-known/acme-challenge/y7HlW6w374Fom8VDkic8mk9LqWXKotNVjNo7Wc1Lo1E` renders an empty string (status 200)
#### 3. Steps to reproduce issue

Install letsencrypt-plugin per directions
Run `rake letsencrypt-plugin`
Receive `Challenge verification failed! Error: urn:acme:error:unauthorized: Invalid response` exception
Visit the URL letsencrypt's server tried to visit
Receive empty string
#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

rails 5.0.0
ruby 2.3.0
letsencrypt_plugin 0.0.9
`challenge_dir_name: ''`

**Comment by b264** [comment]
An error message would be extremely helpful.

**Comment by lgromanowski** [comment]
This is probably connected with "challenge_dir_name" setting in config/letsencrypt_plugin.yml file - please check if it's commented and if not, then please comment it and re-run rake letsencrypt_plugin task again

**Comment by b264** [comment]
It was not commented, it was set to an empty string, per the instructions.  I no longer have this gem to test anything else, because it was not working.

**Comment by b264** [comment]
Adding a `raise` in this instance would have solved this problem.

**Comment by b264** [comment]
The solution is/was to use the certbot version and not this Rails gem.  Closing issue.
