### ISSUE TITLE
Rails - can't rake migrations in Step 3

### ISSUE THREAD

**Issue by MincePie** [lgromanowski/letsencrypt-plugin#52]
_Please use [markdown formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) for code, configuration or console output._
#### 1. Expected behavior

In step 3, I tried to rake db:migrate and expected the migrations to run
#### 2. Actual behavior

Psych::SyntaxError: (/Users/ooo/config/letsencrypt_plugin.yml): did not find expected key while parsing a block mapping at line 2 column 3
#### 3. Steps to reproduce issue

So far, I have setup my config as shown in your readme - but I'm getting stuck at Step 3. I cant run the migrations.
#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

Ruby v 2.3.1; Rails 5, gemfile includes this gem.

**Comment by MincePie** [comment]
For those with the same problem, it's a yml issue. I'm not particularly familiar with yml syntax, but the outer brackets domain: "<%= ['example.com', 'www.example.com'].join(' ') %>" need to be swapped for double quotation marks (the template uses single quotation marks for both the inner and outer. I dont know about yml but I think this is a syntax error. Switching to "" on the outer level resolved this for me.

**Comment by jasper-lyons** [comment]
I've updated the wiki inline with this. Thanks for finding it.
