### ISSUE TITLE
Heroku: Acme::Client::Error::Malformed: Invalid character in DNS name

### ISSUE THREAD

**Issue by MincePie** [lgromanowski/letsencrypt-plugin#53]
_Please use [markdown formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) for code, configuration or console output._
#### 1. Expected behavior

I finished the steps in the installation guide. I'm now trying to run heroku run rake letsencrypt_plugin
#### 2. Actual behavior

I get an error that says:

rake aborted!
Acme::Client::Error::Malformed: Invalid character in DNS name
#### 3. Steps to reproduce issue

I cant find anyone with a similar error, except those using the heroku version of another lets encrypt gem - who at the time, had an issue because multiple domains were not supported by that gem.
#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

Rails 5, Ruby 2.3.1, I have this gem in my gemfile

**Comment by jasper-lyons** [comment]
My comment in https://github.com/lgromanowski/letsencrypt-plugin/issues/54 should sort this out.
