### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by MincePie** [lgromanowski/letsencrypt-plugin#59]
I am trying to figure out how to use lets encrypt to add SSL to my heroku app.

I have been struggling to figure this out for a few months - using this gem and other methods. 

I can't currently render my page using my custom domain name.

#### 1. Expected behaviour
When I try to check the application is serving your certificate by running:

openssl s_client -connect www.mycustomdomainname.com.herokudns.com:443 -servername www.mycustomdomainname.com

I get:

verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /CN=www.mycustomdomainname.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /CN=www.mycustomdomainname.com
verify error:num=21:unable to verify the first certificate
verify return:1

#### 2. Actual behavior 

penssl s_client -connect www.mycustomdomainname.com.herokudns.com:443 -servername www.mycustomdomainname.com
CONNECTED(00000003)
CONNECTED(00000003)
depth=0 /CN=www.mycustomdomainname.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /CN=www.mycustomdomainname.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /CN=www.mycustomdomainname.com
verify error:num=21:unable to verify the first certificate
verify return:1

I can then see:

Certificate chain
 0 s:/CN=www.mycustomdomain.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
Server certificate
-----BEGIN CERTIFICATE----- [which then is followed by the cert]

subject=/CN=www.mycustomdomainname.com
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
---
SSL handshake has read 1459 bytes and written 452 bytes

The last lines of the log read:

 Verify return code: 21 (unable to verify the first certificate)
---
read:errno=0

#### 3. Steps to reproduce issue

I followed the installation instructions as amended by last issue notes.
 
#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)
Rails 5, Ruby 2.3.1, this gem

Thanks so much for your help

**Comment by lgromanowski** [comment]
Hello,
I am sorry but as I mentioned earlier I am not Heroku user and I can not help you - If certificates are visible on console than you should read Heroku docomentation/faq/etc. how to add them on Heroku. 

https://devcenter.heroku.com/articles/ssl-endpoint
https://devcenter.heroku.com/articles/ssl
https://www.google.com/#q=heroku+how+to+add+own+certificate
