### ISSUE TITLE
Added new config option 'cert_name'

### ISSUE THREAD

**Issue by FloHeinle** [lgromanowski/letsencrypt-plugin#61]
Hi @lgromanowski,

thank you very much for this great gem.

I forked it and added a new configuration key 'cert_name' and adopted the wiki.
- If this key isn't set, the first entry in 'domain' is used a the key name, as usual.
- If it is set, its value will be used for the key names.

I think this could be very helpful, because we can set the key name independently from the domains, which could change when saved in db.

I don't have tests for this right now, its just tested on our staging servers.

Will you be happy with a merge request?

commit: https://github.com/FloHeinle/letsencrypt-plugin/commit/2d2528c941c16997d2d7b526e16872a9512abc87

wiki: https://github.com/FloHeinle/letsencrypt-plugin/wiki

**Comment by lgromanowski** [comment]
Hi,
sure, please send a pull request I'll merge it :)

**Comment by FloHeinle** [comment]
Thanks.

Pull request created.
I also edited the wiki.
