### ISSUE TITLE
Rails 5.1+

### ISSUE THREAD

**Issue by halo** [lgromanowski/letsencrypt-plugin#64]
Is there a particular reason to [not support](https://github.com/lgromanowski/letsencrypt-plugin/blob/6d22ebde9f246694c90ba09b80ee507abe45985a/letsencrypt_plugin.gemspec#L25) Rails 5.1 which [was released](https://rubygems.org/gems/rails) several weeks ago?

Whenever a new Rails version is released, I'm prevented from upgrading [because of this](https://github.com/lgromanowski/letsencrypt-plugin/issues/35).

Can we simply not define an upper end to the Rails version?

**Comment by lgromanowski** [comment]
Merged. Thanks for pull request and sorry for late response I've been busy last months

**Comment by halo** [comment]
No worries, I know how that feels :) And now this problem is solved once and for all.

Thank you!
