### ISSUE TITLE
Storing challenge response in the filesystem.

### ISSUE THREAD

**Issue by iainbryson** [lgromanowski/letsencrypt-plugin#8]
Hi,

For those of us using MongoDB (i.e. a non-ActiveRecord DB), the current method of challenge response doesn't work.

Can you introduce a mode to simply store the response in the filesystem instead?  There's no real advantage to hosting this data in the DB -- it won't be accessed or changed often, there's no need for concurrent read/write, etc...

I can do the work if you'd like.

**Comment by lgromanowski** [comment]
Hi,
thanks for pointing this out. It would be nice if you could send me a pull request with needed changes :)

**Comment by lgromanowski** [comment]
Solved in 70c5e29b87682abde42c9e7181b19b7a553d30fe
