### ISSUE TITLE
how do you use this gem in heroku?

### ISSUE THREAD

**Issue by keating** [lgromanowski/letsencrypt-plugin#9]
When I run the command
`heroku run rake letsencrypt_plugin RAILS_ENV=production`

The output is correct like the Readme, but heroku does not save the files generated, so I can not get the CSR/key files ...

There is a question for heroku file system. http://stackoverflow.com/questions/21465789/how-can-i-download-a-file-from-heroku-bash

**Comment by lgromanowski** [comment]
Hi
in current master certificates are now displayed on console :)

**Comment by keating** [comment]
Cool, great work ! Now I can get ssl key/crt on heroku !
Thanks a lot, happy new year !
